services:
  - type: web
    name: django-app
    runtime: python
    plan: standard  # Для production используйте минимум standard (free для тестов)
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput

    startCommand: |
      gunicorn config.wsgi:application \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --threads 2 \
        --timeout 120 \
        --keepalive 32

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ALLOWED_HOSTS
        value: "dpg-d0iu8cq4d50c73dvtj50-a.oregon-postgres.render.com *.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: dbname_a2fl
          property: connectionString
      - key: REDIS_URL
        value: redis://redis-db:6379/0  # Если используете Redis

databases:
  - name: dbname_a2fl
    plan: free  # Для production выберите paid план
    ipAllowList: []